### ISSUE TITLE
Add links to higher-resolution images

### ISSUE THREAD

**Issue by dkirkby** [dkirkby/legacyQA#6]
A suggestion from Eddie on [decam-chatter]:

It would be great to be able to conveniently get higher resolution versions.  The viewer makes individual chips available as follows http://legacysurvey.org/viewer/ccd/decals-dr7/decam-723820-S22-r

**Comment by dkirkby** [comment]
The number 723820 appearing in the sample URL above is encoded as EXPNUM in one of the FITS headers (presumably HDU[0]).

**Comment by dkirkby** [comment]
Extracting EXPNUM from the .fits.fz files is painfully slow (almost 1 sec per file), presumably because of the decompression overhead.

@schlafly @dstndstn @moustakas Any idea if the CP output <-> EXPNUM mapping is already written out to a file somewhere?

For example:
```
CP20140810_g_v2/c4d_140815_235550_ooi_g_v2.fits.fz <-> EXPNUM 348225
```

**Comment by dstndstn** [comment]
You can use the survey-ccds*.fits files from a DR to find this mapping; the columns are image_filename and expnum.

**Comment by moustakas** [comment]
And unfortunately the only CCDs files we have right now (based on an old, incomplete image list) are split by per-band, but can be found here:
`/global/project/projectdirs/cosmo/work/legacysurvey/dr8-attic-2/DECaLS`

Calibs are top priority and then we'll have the definitive `survey-ccds` file.

**Comment by schlafly** [comment]
The -ondisk files you're working from also have the expnum-file name mapping; that's the easiest route forward.

**Comment by dkirkby** [comment]
Is the naming of CP outputs documented somewhere?  For example, in `/global/project/projectdirs/cosmo/work/legacysurvey/dr7/survey-ccds-dr7.fits.gz` I see names like:
```
decam/DECam_CP/CP20160107/c4d_160103_082125_ooi_g_v1.fits.fz
```
In `/global/project/projectdirs/cosmo/work/legacysurvey/dr8-attic-2/DECaLS/survey-ccds-decam-g.fits.gz` I see names like:
```
decam/DECam_CP/CP20180318/c4d_180319_022328_ooi_g_v1.fits.fz
```
Finally, in `/global/project/projectdirs/cosmo/work/legacysurvey/dr8b/image-lists/image-list-decam-dr8.txt`, I see:
```
decam/DECam_CP/CP20140810_g_v2/c4d_140815_235550_ooi_g_v2.fits.fz
```
I guess the 8 digits after CP are a date and v1 and v2 are version numbers, but then why is v2 associated with 2014 and v1 associated with both 2016 and 2018?

Presumably v2 is what will be used for DR8, so is what I should be using to create full focal-plane thumbnails?

**Comment by schlafly** [comment]
This looks like it's what you want:
http://ast.noao.edu/sites/default/files/File_Naming_Conventions_v12.pdf
But here's my summary...
c4d: CTIO 4 meter DECam
160103_082125: image taken on 2016-01-03:08:21:25---I can't remember the time zone, etc., used for computing this time.
ooi: three letters indicating what type the file has.  Initial 'o' is 'object', the second 'o' means 'InstCal' (the stage of processing we usually use); the final letter is one of 'iwd' for the images we use, corresponding to image, weight, dq mask.
The next letter is the filter.  The 'v1', etc., prefix has no consistent meaning---something of a problem.  It gets added by hand to distinguish between different processing versions, and will have different meaning depending on year/camera/....

For DR8 you should use whatever files are in the image list; we're using all of those.  I don't know why that particular image from 2014 got reprocessed and a v2 got appended.  Reviewing my email, it looks like a bunch of CP improvements were recommended for this early data, and after these were incorporated the data was reprocessed through the CP with those improvements.

**Comment by schlafly** [comment]
And to elaborate here:

> Any idea if the CP output <-> EXPNUM mapping is already written out to a file somewhere?

I think the easiest thing is to use
`/global/project/projectdirs/cosmo/work/legacysurvey/dr8b/image-lists/dr8-ondisk-decam-v4.fits`
for this mapping.

**Comment by moustakas** [comment]
Let's start using
` /global/project/projectdirs/cosmo/work/legacysurvey/dr8/image-lists/`
please, and freeze the `dr8b` directory.

**Comment by dkirkby** [comment]
I am almost done with adding this feature.  I guess for now the high-resolution image will have to be from DR7 since http://legacysurvey.org/viewer/ccd/decals-dr8 is not up yet?

**Comment by schlafly** [comment]
Yes, we'll need to do DR7; it will be a while before DR8 is fully in the viewer.
